# -*- coding: utf-8 -*-

IGNORE = ["Business Development", "Business", "Sales", "Human Relation", "Market research", "Market", "Marketing", "Finance", "Recruitment", "Human Resources", "HR", "Manufacturing", "admin", "reception", "desk manager", "desk", "recruiter", "accountant", "Database Administrator", "construction", "customer", "Purchase", "procurement", "technician", "Assembly", "planner", "Buyer", "Supervisor", "management", "purchasing", "buying", "trade", "financial", "quality", "compensation", "compensation & benefits", "compensation and benefits", "production", "warehouse", "operations", "maintenance", "inventory", "logistics", "plant manager", "process", "delivery manager"]

BU_keywords = {
    "Ford Motor Company": {
        "Body Engineering": ["Body Engineering","safety analysis","Interior and exterior systems","climate control","Instrument panels","consoles","seats","restraints","carpeting, headliners","door panels","sheet meta","front end grilles","glass and other interior and exterior trim components","Globe box","Front Scuff","Rear Scuff","Tow Bar holder","Wiper Motor Cover","Demist Duct","Hood","Deck lid","Roof","Dash Assembly","Underfloor","Body In White","BIW","safety","Exterior Body","Interior","climate control","HVAC","Instrument Panel","Console"," seat belt","Headliner","Carpet","Door handle","ODH-IDH","5 door","2door","Door","Sheet Metal","Grille","Pillar trim","Cowl side Trim","Interior Trim","upper Hard trim"],
        "Chassis Engineering": ["spacer wheel","braking system","framing","Chassis","Chassis Engineering","suspension systems","frames","subframes","steering","foundation brakes","wheels","tires","chassis electronics","stability control","traction control ","regenerative braking"],
        "Connected Services Solution": ["car play","Connected services solution","SYNC","SYNC Gen 3","SYNC ecosystem","SYNC intergrated system","sync gen","in-vehicle telematics","telematics control","telematics"],
        "Powertrain Installation": ["powertrain","powertrain installations","PTI","power train","exhaust","exhaust system","air induction","engine mounts","engine","cooling system","electrified powertrain","calibration","battery","batteries","motors","motor & system",'motor and system',"battery electric vehicles","plug in hybrid","HEV","Hybrid electric vehicles","motor compartment","battery assembly","battery management system"],
        "Global Engine Engineering": ["Engine","engine components","engine technology","engine technologies"],
        "Electrical & Electronic System Engineering": ["infotainment","body electronics","Driver Controls","Active Safety","Power Supply Systems","ADAS","Advanced driver assistance systems","power supply"]
    },
    "Continental": {
        "Chassis Engineering": ["Vehicle Dynamics","Electronic brake systems","Electronic air suspension systems","Chassis Domain Control Unit","Regenerative brake systems","Hydraulic Brake Systems","Disc brakes","Drum brakes","Brake Shoe","Electronic Parking Brake (EPB) systems","Brake actuation systems","Mechanical and electronic brake assist systems","Brake hoses","Passive Safety and Sensorics","Crash Impact Sound Sensors","CISS","Crash sensors","Chassis position and acceleration sensors","Intelligent Battery Sensors","IBS","HighVoltage Current Sensor","CSM","Sensors for electric vehicles","Pedal Angle Sensor","PAS","Accelerator Force Feedback Pedal","AFFP","Steering angle sensors","Torque sensors","Active wheel speed sensors ","Engine/transmission speed and position sensors","Buckle switch sensors","ECU","Brake pad wear indicator","Cam sensor","Crank sensor","Advanced Driver Assistance Systems","Adaptive cruise control","Blind spot detection","Rear cross traffic alert","Emergency brake assist","Intelligent headlamp control","Lane departure warning","Traffic sign recognition","Surround view systems","Speedo Meter","Hour Meter","Washer Systems","Hoses and connectors","Nozzles","Pumps","Reservoir systems","Pressure Sensor","PS100","TMAP senors","synerject sensor","Actuation System","Brake booster","TMC","Brake Actuation system","ACU","Electric Parking Brake","EPB","Automated Parking Brake","Parking Brake","iEPB","Reverse Parking Aid","Brake shoe","Drum brake","Disc Brake","Brake Calipers","Caliper","Front Disc Brake","Rear Disc Brake","Rear Caliper","Disc Rotors","Chassis Control","Brake","Conti Brake","Automotive Brake ","Electronics Braking System ","braking system ","MK100"," MKC1","Electronics Brake System","EBS","Tandem Master Cylinder","Master & Wheel Cylinders"],
        "Powertrain Engineering": ["Engine Systems","Diesel Piezo common rail injection systems","injection systems","Gasoline direct injection systems","Diesel and gasoline high pressure pumps","Gasoline port fuel injection","fuel injection","Engine Management System","EMS","Liquefied Petroleum Gas","LPG","Compressed Natural Gas","CNG","injection systems","Turbochargers","Exhaust gas aftertreatment systems","Transmission","Transmission control units","Transfer cases","Differentials ","Limited slip coupling","Hybrid Electric Vehicle","HEV","Power electronics","Electric motors","Liion battery systems","lithium ion","Li- ion","battery systems","Energy management systems","Power net systems","48V EcoDrive","Actuators","Sensors","Flex fuel sensors","Oil fluid level sensors","Urea concentration and fluid level sensors","Incylinder pressure sensors","Knock sensors","Mass airflow sensors","Natural vacuum leakage detection","Position sensors","NOx sensors","Particulate matter sensors","Temperature sensors","Engine actuators","valves","Air control valves","Idle air control valves","Electronic throttle controls","Electrical water pumps","Transmission oil pumps","Coolant pumps","Variable lift controls","Emission actuators","Electrical compressor bypass valves","Electrical exhaust gas recirculation valves","Exhaust control valves","Purge solenoids and valves","valves","purge solenoids","solenoids","Load Sensitive proportional Valve","Fuel & Exhaust Management","Fuel supply electronics","Fuel level sensors","Fuel pumps","Fuel delivery modules","Catalytic converters","Pump control electronics","Pressure regulators","Modular function carriers with carbon canister","venting system","Anti Pinch Window Regulator","fuel"],
        "Body Interior": ["Body & Security","Body control modules","Door systems","Power closure systems","Seat comfort systems","Access control systems","Exterior light control units","Tire information systems","Antenna modules","Gateways","Energy management systems","Connectivity","Telematics","Device connectivity","Seamless mobile integration ","Commercial Vehicles and Aftermarket","Tachographs and services","Instrumentation and telematics","Control systems","Visual Display Systems","Instrument clusters","Secondary displays","Headup displays","Control Elements","Climate control units","Cockpit modules","Haptic controls","Roof modules","Integrated centerstacks","Infotainment","eHorizon navigation systems","Multimedia systems and platforms","Flat panel radios","Remote Keyless Entry"],
        "Conti Tech Division": ["Air Spring Systems","Air actuators","pneumatics","vibration isolation","Compensators","BeneckeKaliko Group","Foil","coated fabrics","Molded slush skins","Expanded vinyl","Compounding Technology","Rubber compounds","Sealing systems","Elastomer Coatings","Gas holder diaphragms","Collapsible tanks","Concertina walls","Fuel cells","Elastomer sheetings","Fluid Technology","Hoses","Power Transmission Group","Multiple Vribbed belts","Timing belts","Flat belts","Belt drive systems","Vibration Control","Hydromounts","Mounting systems","Adaptive mounts","Spring strut mounts","Seat suspension","Dynamic vibration absorber","Torsional vibration absorber","Bushings"],
        "Tyres Division": ["Passenger truck tires","Runflat tires","Selfsealing tires","Tire noise reducing technology","Commercial vehicle tires","Tire pressure monitoring system","Pressure monitoring","tires","Light truck tires","Passenger truck tyres","Runflat tyres","Selfsealing tyres","Tire noise reducing technology","Commercial vehicle tyres","Tire pressure monitoring system","Pressure monitoring","tyres","Light truck tyres"]
    },
    "Autoliv": {
        "Passive Safety Systems": ["Driver airbags","Passenger airbags","Knee airbags" , "Antisliding airbags" , "Sidecurtain airbags" , "Side airbags" , "Rear passenger airbags" , "Thorax" , "Headthorax" , "Door mounted" , "Pelvis/thorax" , "Farside airbags" , "Baginbelt airbags" , "Child restraint" , "Pyrotechnic airbag" , "Stored gas airbag inflators" , "Electrical initiators" , "Micro gas generators" , "Fixedhub steering" , "Steering wheels" , "heated rim" , "Belt grabbers" , "Beltsinseat" , "Buckles" , "Height adjusters" , "Load limiters" , "Pretensioners" , "Retractors" , "Smart belts" , "Trunk belts" , "Supplemental belts" , "Pyrotechnic hoodlifters" , "Pedestrian Protection Airbag" , "Antiwhiplash systems" , "Battery disconnect" , "Airbag" , "Air Bag" , "Airbags"],
        "Active Safety Systems": ["ECU" , "Satellite sensors" , "Electronic safety" , "Restraint control" , "ESC" , "Traction control" , "Antilock braking" , "Blind spot detection" , "LIDAR" , "Long range radar systems" , "Monovision camera" , "Stereovision" , "seatbelt"]
    },
    "Bosch": {
        "Gasoline Systems": ["Direct injection" , "Fuel injection" , "Flex fuel" , "Accelerator pedal modules" , "Electronic throttle" , "ECU" , "Electric fuel" , "Intank fuel" , "Fuel injector" , "fuel rail" , "fuel tank leakage" , "Cylinder head covers" , "Oil separators" , "Canister purge valve" , "Plugin connections" , "Secondaryair pumps" , "Intake modules" , "Singlespark ignition" , "Ignition coil" , "Power system" , "ECU actuators" , "ECU" , "Continuously Variable Transmission " , "CVT" , "Boost Recuperation" , "Engine management sensors" , "Exhaust management" , "Transmission speed" , "Gasoline System" , "Gasoline" , "engine Component"],
        "Diesel Systems": ["Common rail" , "Unit injector " , "Injection nozzles" , "Lowpressure " , "Axialpiston" , "Unit Pump" , "Singlecylinder" , "Inline pumps" , "Glow control" , "Glow plugs" , "Intake air" , "Throttle valve" , "Exhaust gas" , "Plastic control" , "Swirl actuators" , "Boost pressure" , "Exhaust gas turbocharger" , "Hotfilm airmass meter" , "Air temperature " , "Boost pressure " , "NOx catalytic converters" , "Accumulatortype" , "Particulate filter " , "Denoxtronic SCR " , "Diesel Particulate Filter" , "Engine management " , "Exhaust management "],
        "Hv/Ev Systems": ["Electric machine" , "Inverters" , "regenerative braking" , "High voltage" , "Vacuum pumps" , "Hydrogen Fuel" , "Hydrogen Car" , "Alternate Fuel" , "Electric Car" , "Hybrid Fuel" , "Hybrid Car" , "Fuel Cell" , "HEV" , "PHEV" , "Plug In Hybrid" , "battery" , "electric battery" , "electric vehicle" , "EV" , "xEV" , "electronic drivetrain" , "lead acid battery" , "HV battery" , "Hydrogen Tank" , "Electric motor" , "Hybrid vehicle" , "Hybrid drivetrain" , "Hybrid Drivetrain" , "Parallel hybrid" , "Through The Road Hybrid" , "Series hybrid" , "Power-split hybrid" , "Two-Mode Hybrid" , "Hybrid Synergy Drive" , "Micro hybrid" , "Plug-in electric" , "Battery electric vehicle" , "Regenerative Braking" , "Electric Powertrain" , "Hybridfahrzeug" , "hybrid vehicles" , "electric drive" , "Electric Vehicle" , "Battery Systems" , "Electric Engine" , "Hybrid traction" , "Battery Charging" , "Battery Management System" , "BMS" , "Hybrid systems" , "Electrified Powertrain" , "Lithium" , "Li-ion battery" , "Inverter" , "Inverters" , "Electric Propulsion" , "Hybrid" , "Electric Systems" , "Electric System" , "Electric Energy" , "Electric Vehicles" , "Electric Motor" , "Propulsion System" , "Propulsion Systems" , "Electric Motors" , "DC Converter" , "eDrive" , "Plug In Hybrids" , "Electric Drivetrains" , "Electric Drivetrain" , "BEV" , "Electrified Propulsion" , "Powertrain Electrification" , "HV/EV"],
        "Chassis Systems Control": ["Vacuum pumps" , "fuel vaccum pumps" , "Brake boosters" , "Electric brake boosters" , "Tandem master cylinders" , "Hydraulic boosters" , "Emergency Valve Assist" , "Antilock Braking System" , "Traction control systems" , "ESP" , "Adaptive Cruise Control" , "Intelligent headlight" , "Road sign recognition" , "Parking aid" , "Side view" , "Night Vision Plus" , "Driver drowsiness" , "Predictive emergency" , "Lane assist" , "Predictive pedestrian" , "Construction zone" , "longrange radar" , "Multipurpose cameras" , "Crash detection" , "Airbag control sensors" , "Pedestrian protection" , "Airbag control" , "Peripheral acceleration" , "Pedestrian contact"],
        "Electrical Drives": ["Window lift" , "Sunroof drives" , "Seat actuators and drives" , "Steering column drives" , "Climate control systems" , "Engine thermal management" , "Blower modules" , "Engine cooling" , "Engine cooling" , "Engine cooling valves" , "Wiper" , "Windshield" , "Wiper blades"],
        "Starter Motors And Generators": ["Starters" , "Generators " , "Start/Stop motors"],
        "Car Multimedia": ["Invehicle" , "Sound systems" , "navigation" , "Radio HiFi" , "Infotainment" , "mySPIN" , "Headup Display" , "instrument cluster" , "DualView"],
        "Automotive Electronics": ["Multiplex systems" , "Electric/Electronic architectures" , "Immobilizer" , "ASICs/ASSPs" , "Diodes" , "IP modules" , "MEMS" , "Body electronic control" , "Braking control" , "Engine management systems" , "Various control units" , "Steering" , "Steering columns" , "Electro Hydraulic Power Steering" , "Power Steering" , "Steering angle sensors" , "Steering torque sensors"],
        "Automotive Steering": ["Steering" , "Steering columns" , "Electro Hydraulic" , "Power Steering" , "Steering angle sensors" , "Steering torque sensors"]
    },
    "Valeo": {
        "Powertrain Systems": ["Powertrain Systems","Electrical Systems","Starters","Alternators","Battery management systems","Electric retarders for trucks and buses","Charger  Inverter","Stopstart systems","Mild hybrid systems with regenerative braking","Full hybrid/rechargeable hybrid systems","Transmissions","Cover assemblies","Discs","Clutch facings","Release bearings","Hydraulic clutch actuators","Dual mass flywheels","Flexible flywheels","Systems for automated manual transmissions","Torque converters","Lockups","Dry double clutch","Combustion Engine Systems","Complete engine management systems for gasoline and diesel engines","Engine control units","Electric motor drives","Ignition components","Emission control systems","Injectors","Sensors","Hydraulic control","Energy Management" , "Intelligent Battery Sensor" , "IBS","Hybrid components" , "braking system compressor"],
        "Thermal Systems": ["Thermal Systems","Climate Control","Airconditioning systems and modules; airconditioning loops and modules, including evaporators and heater cores","Decentralized interior comfort modules; rear air conditioning devices, boosters, additional comfort modules","Air quality products; air filtration and purification systems","Powertrain thermal systems","Thermal management systems for powertrains","Battery thermal management systems","Cooling modules","Condensers","Exhaust gas recirculation cooling systems","Exhaust gas coolers","Evaporators","Heater cores","Charge air coolers","Fuel coolers","Exchangers of oil","Oil temperature management systems","Fans/Motor systems","Charge air cooler modules","Front end modules","Active Grille Shutter","Radiator tanks","Air intake modules","A/C black boxes","Compressors","Pallet compressors","Fixedcylinder compressors","Variable cylinder compressors","Electric and scroll technology compressors","semihermetic","Front end modules","Modules which include fan motors, heat exchangers, lighting systems, safety features, horn, cables, radar and cameras","Electronically controlled shutters","Fuel Control Module","Gas Injection Equipment","open compressors"],
        "Comfort and driving assistance systems": ["Comfort and Driving Assistance Systems","Driving Assistance","360Vue multicamera systems","Lane change assistance systems","Cross traffic alert systems","Lane departure warning systems","Semiautomatic parking assistance systems","Ultrasonic sensors","Infrared sensors","Radar sensors","Infrared laser scanner","Interior Electronics","Handsfree access and start systems","Connectivity to mobile phone networks","Access to car sharing services and remote parking systems","Body controllers","Interior Controls","Top column modules","Cabin comfort controls and control panels","Steering angle sensors; angle and torque sensors","Electronic control units","Integrated faceplate","Steering column switch modules","Window lift switches","Touch screen","Rain light sensors","Accelerator padel sensor","Oil level sensor","Body electronics","Body control module", "Remote keyless entry"],
        "Visibility Systems": ["Visibility Systems","Lighting Systems","Main and auxiliary headlamps; halogen and Xenon","LED front lightings","Adaptive front lightings","Fog lights","DRL daytime lamps","Leveling devices and lamp wipers","Lighting controllers","Rear lighting including LED rear lamps and center highmounted stop lamps","Cabin lightings","Cigar lighters","Wiper Systems","Arms","Blades","Linkages","Motors","Wash systems","Front and rear wiper modules"]
    },
    "Denso": {
        "Powertrain Systems": ["Electric and Hybrid Vehicles","EV/HEV","Inverter PCUs","Power control units","PCUs","Motor generators","DC converters","AC/DC","Battery monitoring units","BMU","Battery current sensors","System main relays","Hybrid vehicle electronic control units","HVECU","ECU","Engine Management System","Engine electronic control units","Engine ECU","Air flow meters","Electronic throttle bodies","Accelerator pedal modules","Variable intake air control valves","air control valves","pressure sensors","Air filter elements","Air filter","Air induction systems","induction system","Integrated airfuel modules","airfuel module","Variable cam timings","Oil flow control valves","Fuel injectors","Fuel pumps","Fuel pump modules","Fuel filters","Fuel tank pressure sensors","Pressure regulators","Fuel pulsation dampers","Evaporative purge valves","Canister close valves","valves","Evaporative leak check modules","High pressure pumps","High pressure injectors","gasoline direct injection","Ignition coils","Iridium spark plugs","Cam position sensors","Crank position sensors","Knock sensors","Oxygen sensors","AirFuel ratio sensors","Thin wall hexagonal cell substrates","Combination valves","Diesel Engine Management System","Engine electronic control units","Intake heaters","temperature sensors","throttle bodies","Supply pumps","Solenoid injectors","Rails","Common rail pressure sensors","Ceramic glow plugs","Exhaust gas recirculation valves","EGR valves","EGR gas temperature sensors","Exhaust gas temperature sensors","Diesel particulate filter","NOx reduction systems","Exhaust gas pressure sensors","Powertrain Cooling System","Reserve tanks","Radiators","Cooling fans","EGR coolers","Inter coolers","Oil coolers","Cooling fan controllers","Coolant temperature sensors","Oil filters","Transmission Control System","Automatic Transmission PWM solenoids","Automatic Transmission linear solenoids","Automatic Transmission control valves","Shiftbywire actuators","Speed sensors","Starters","Alternators","Battery packs","Fire fighting system ","Speedometer","Gasoline Calibration","Engine Management System","Engine ECU","Air Bag CU","VCT","ISCV","Injection Molding Technology","fuel line","injector line","Diesel fuel injector","Fuel injection system","FIS","UCInjector","Common Rail System","CRS"],
        "Climate Control": ["HVAC units","Evaporators","Heater cores","Condensers","Compressors","Blower motors","Servo motors","Cabin air filters","Air purifiers","Rear cooling units","Incar sensors","In car sensors","in-car sensors","Matrix IR sensors","IR sensors","Solar sensors","Humidity sensors","Evaporator temperature sensors","Refrigerant pressure sensors","Brushless motor controllers","Climate control panel","Air conditioner","Boiler","Chillers","heat exchangers","Centrifugal Chiller"],
        "Driver Control & Safety": ["Driving assist system","Millimeter wave radar sensors","Laser radar sensors","Vision sensors","Driving assist electronic control units","Assist ECU","Sonar sensors","Seatbelt ECU","Environment monitoring cameras","Driver status monitors","Lighting control system","Adaptive frontlighting system controllers","High intensity discharge lamp ballasts","Steering system","Electric power steering motors","Electric power steering electronic control units","Electric power steering integrated with ECU","Steering torque sensors","Variable gear ratio steering motors","variable gear ratio","Variable gear ratio steering electronic control units","steering ECU","Airbag system","active safety","Accelerometers","Satellite G sensors","Airbag electronic control units","Airbag ECU","Pedestrian collision detection sensors","collision detection","Passenger detection sensors","Brake control system","Brake pressure sensors","ESC units","Wheel speed sensors","Inertia sensor for ESC systems","Accelerometers for suspension","O2 Sensor","LVDT/MDVRT"],
        "Information & Communication Division": ["Human Machine Interface","HMI","Car navigation systems","Integrated antennas","Optical beacon antennas","Instrument clusters","Headup display units","Remote touch controllers","Data Communication System","Data communication modules","DCM","Vehicle to vehicle","vehicle to infrastructure","V2V","V2I","Security System","Smart keys","Remote security units","Security cameras","ETC system","electronic toll collection system","2.0 onboard equipment","antenna","Automated Optical Inspection"],
        "Body Electronics": ["Body Electronics","body ECU","Tire pressure monitoring","TPMS ECUs","Solar sensor","twilight sensors","Horns","Rain sensors","Windshield washer systems","Windshield wiper systems","Power window regulator motors","Remote keyless entry buzzers","Power printed circuit board relays","Low profile micro ISO relays","Power Mini ISO relays","IC Flashers"]
    },
    "Microsoft": {
        "Intelligent Cloud": ["Enterprise Services","Microsoft Consulting Services","Premier Support Services","Server products","Cloud services","Advanced Threat Analytics","API management","App Service","Application Gateway","Azure Active Directory","Azure Active Directory Domain Services","Azure Bot Service","Azure Container Registry","Azure Container Service","Azure DevTest Labs","Azure DNS","Azure Information Protection","Azure IoT","Azure StorSimple","Backup","BizTalk","BizTalk Services","Blob Storage","CDN","Cloud App Security","Cloud Services","Cognitive Services","Compute","Converged systems","Data Factory","Data Lake Analytics","Data Lake Store","Databases","Developer Tools","Developer Tools and SDKs","DocumentDB","Enterprise Integration","Event Hubs","ExpressRoute","File storage","HDInsight","Health Intelligence","HockeyApp","Identity for developers","Intelligence + Analytics","Internet of Things","Key Vault","Load Balancer","Logic Apps","Machine Learning","Microsoft Azure","Microsoft Azure Stack","Microsoft Identity Manager","Microsoft Intune","Microsoft Power BI","Microsoft R Server","Monitoring + Management","Multi-Factor Authentication","Networking","Notification Hubs","Power BI Embedded","Premium Storage","Queue Storage","Redis Cache","Security + Identity","Security Center","Service Bus","Service Fabric","Site Recovery","SQL Data WarehouseE","SQL Database","SQL Server","SQL Server Stretch Database","Storage","Storage Explorer","StorSimple","Stream Analytics","System Center 2016","System Center Configuration Manager","Table Storage","Traffic Manager","Virtual machine","Virtual Machine Scale Sets","Virtual Machines","Virtual Network","Visual Studio","Visual Studio Application Insights","Visual Studio Team Services","VPN Gateway","Web + Mobile","Window Server 2016","Windows Azure Pack","Xamarin"],
        "More Personal Computing": ["Devices","Headsets","Hololens","Keyboard","Lumia","Mice","Microsoft band","Surface","Surface 3","Surface Hub","Surface Pro","Surface tablets","Webcam","Gaming","Project Scorpio","Xbox","Xbox 360","Xbox 360 Controller","Xbox 360 Dashboard","Xbox 360 Kinect","Xbox Controller","Xbox Live","Xbox Live Marketplace","Xbox One","Xbox One Controller","Xbox One Dashboard","Xbox One Kinect","Xbox SmartGlass","Search Advertising","Bing","Bing ads","Search Advertising Total","Windows","Internet Explorer","Microsoft Edge","MSN","Windows 10","Windows 7","Windows 8.1","Windows Embedded","Windows Vista"],
        "Productivity And Business Process": ["Microsoft Dynamics","Dynamics CRM Online","Dynamics CRM on-premises","Dynamics ERP products","Office Commercial","Exchange","Office","Office 365","SharePoint","Skype for Business","Office Commercial Total","Office Consumer","Office 365","OneDrive","Outlook.com","Skype"]
    },
    "Google": {
        "Advertising Services": ["Adwords Express","DoubleClick","DoubleClick for Publishers","Google Ad Planner","Google AdSense","Google AdWords","Google Certification Program","Google Grants","Google Think Insights"],
        "Communication And Publishing Tools": ["Blogger","Boutiques.com","FeedBurner","Gmail (also termed Google Mail)","Google 3D Warehouse","Google Apps for Work","Google Art Project","Google Bookmarks","Google Business Solutions","Google Calendar","Google Classroom","Google Cultural Institute","Google Docs","Google Domains","Google Drive","Google Fonts","Google Hangouts","Google Helpouts","Google Inbox","Google Keep","Google Play Music","Google profile","Google Sites","Google spaces","Google URL Shortener","Google Ventures","Google Voice","Google+","Panoramio","Questions and Answers ","SMS Channels","Speak To Tweet","YouTube"],
        "Desktop Applications": ["AdWords Editor","Android Studio","Google Chrome","Google Drive","Google Earth","Google Input Tools","Google Japanese Input","Google Photos Backup","Google Pinyin","Google Toolbar","Google Web Designer","Nik Collection"],
        "Development Tools": ["Dart","Google App Engine","Google Developers ","Google Go","Google PageSpeed Tools","Google Search Console","Google Swiffy","Google Web Toolkit","OpenSocial","Translator Toolkit"],
        "Hardware": ["Chromebook","Chromebook Pixel","Chromebox","Chromecast","Chromecast Audio","Chromecast Ultra","Galaxy Nexus","Google Cardboard","Google Contact Lens","Google Daydream","Google driverless car","Google Glass","Google Home","Google OnHub","Google Search App","Google TV","Nexus 10","Nexus 4","Nexus 5","Nexus 5X","Nexus 6","Nexus 6P","Nexus 7 ","Nexus 9","Nexus One","Nexus Player","Nexus Q","Nexus S","Pixel C","Pixel smartphone"],
        "Map-Related Products": ["Build with Chrome","Google Map Maker","Google Maps Gallery","Google Mars","Google Moon","Google My Maps","Google Santa Tracker","Google Sky","Google Street View","Google Transit","Zygote Body "],
        "Mobile Applications": ["Blogger Mobile","Catalogs","Drive","Gmail","Google Authenticator","Google Calendar","Google Currents","Google Goggles","Google Keep","Google Keyboard for IOS","Google Maps","Google News","Google Now","Google Offers","Google Photos","Google Play Books","Google Play Music","Google Play Newsstand","Google Product Search","Google Search","Google Search for Android","Google Sync","Google Talk","Google Translate","Google Voice app","Google Wallet","Google+","Hangouts","Listen","Maps Navigation","Mobilizer","One Today","Shopper","Sky Map","Tango","Translate","Waze","Who's Down","Yinyue","YouTube","YouTube Remote"],
        "Operating Systems": ["Android","Android Auto","Android TV","Android Wear","Chrome OS","Glass OS","Google Fuchsia","Google TV","Television Fanatic"],
        "Search Tools": ["Google Alerts","Alerts","Google Books ","Books ","Google Custom Search","Custom Search","Google Finance","Google Flight Search","Flight Search","Google Groups","Google Hotel Finder","Hotel Finder","Google Image Search","Image Search","Google News","Google Patent Search","Patent Search","Google Recipe View","Recipe View","Google Scholar","Google Video","Knowledge Graph","Language Tools","Life Search","Movies","Suggest","Web History ","Zagat"]
    },
    "Harman International": {
        "Connected Car": ["Intelligent Navigation","Embedded Infotainment","Platform Based Design"],
        "Lifestyle Audio": ["Audio","Dirac","Dira Live ","Dirac Unison ","Dirac Dimension","Dirac Virtual Center","Dirac Panorama Sound","Halosonic","Active Noise Cancellation","Road Noise Cancellation","Engine Order Cancellation","Electronic Sound Synthesis","Bluetooth","Speaker","Luxury Audio","Embeded Audio","Advanced Software","Headphones","AV Receivers"]
    },
    "Johnson Controls": {
        "Building Efficiency": ["AD","VAV","AirSide Systems","Air Handling Systems","Chiller Solutions","Chiller integration","Building Automation Systems"," connected chiller","Cyber Security","Lighting Services","Water Services","Residential Engineering","Control systems","HVAC","Air system"],
        "Automotive Experience": ["Seating","foam","trim","fabric","instrument panels","floor consoles","door panels"],
        "Power Solutions": ["Micro-hybrid products","Advanced Battery","Advance Lead Acid Product"]
    },
    "Fiat Chrysler": {
        "Manufacturing/Materials": ["Tooling Development" , "CAD" , "CAM" , "CAE" , "BIW Design"],
        "Ict": ["Autonomous Driving" , "Adaptive Cruise Control" , "Forward Collision" , "Lane Departure" , "Lane Assist" , "Blind Spot" , "Vehicle Robotics" , "Electric Systems" , "HMI" , "Human Machine" , "Body Control Module" , "Cyber Security"],
        "Powertrain": ["Engine Control" , "Transmission Control" , "Hybrid Vehicle" , "Throttle" , "Valves" , "Power Shafts" , "Driveline Control" , "Chassis" , "Suspension" , "Steering"],
        "Safety": ["Electronic Horizon" , "Collision Avoidance" , "Control Systems"]
    },
    "ZF TRW": {
        "Car Powertrain Technology": ["Electric drives","Hybrid systems","Control Systems ","Clutches","Torque converters","Starting systems","Engine mounts","Corner Modules"],
        "Car Chassis Technology": ["Tie rods","Suspension ","Chassis","Leveling Systems","Control arms","Torque rods","Software","Diagnosis tools"],
        "Steering": ["Hydraulically Powered Steering","Hydraulic Steering","Powered Steering","COLUMN DRIVE EPS","RACK/BELT DRIVE EPS","Transmission Pumps","COMPACT HIGH EFFICIENCY PUMPS"],
        "Occupant Safety": ["Airbags","Pyrotechnic Inflators","single-stage inflator","dual-stage inflators","Actuators","hoodlifters","Pedestrian Protection","SELF ADAPTIVE LOAD LIMITER","SWITCHABLE LOAD LIMITER","ILLUMINATED SEAT BELT BUCKLE","SMALL BUCKLE","DYNAMIC LOCKING TONGUE","Active Buckle","ILLUMINATION TECHNOLOGY","VIBRATING STEERING WHEEL","HANDS ON/OFF DETECTION","Air Bag"],
        "Integrated Systems": ["Driver Assist Systems","Forward Collision","Adaptive Cruise Control","Collision Mitigation","Lane Departure","Lane Keeping Assist","Lane Centering Assist","Active Control Retractor","ENHANCING OCCUPANT SAFETY","ADAS"],
        "Electronics": ["Safety Domain","Integrated Inertial","Crash Sensors","REMOTE ACCELERATION SENSOR ","REMOTE PRESSURE SENSOR","AC3 77 GHz ","AC100 24 GHz ","AC1000 79 GHz ","forward collision","following distance indication","lane departure","automatic high-beam control","speed limit sign recognition"],
        "Body Control Systems": ["Capacitive touch sensing","Contactless switching","Waterproof design ","Clocksprings","Steering angle sensors","Steering column locks","Ignition switches","Mirror switches","Electric park brake switches","Seat adjuster switches","Radiant Sensing Modules","Mechanical Steering","Electrical Steering"],
        "Braking": ["ABS","Electronic Stability Control","Hydraulic Brake","Foundation Brakes","Front Calipers","Colette Calipers","Rear Calipers","FBC CALIPER","OPPOSED PISTON CALIPER","Drum Brakes","Emergency Braking","Rollaway Prevention","Dynamic Braking","Static Braking","EPB","ESC-Hybrid","Slip Control Boost","Integrated Brake Control"]
    }
}

Company = {
    "Bosch": "Robert Bosch GmbH",
    "Microsoft": "Microsoft Corporation",
    "Continental": "Continental AG",
    "Autoliv": "Autoliv",
    "ZF TRW": "ZF TRW",
    "Fiat Chrysler": "Fiat Chrysler Automobiles",
    "Johnson Controls": "Johnson Controls",
    "Harman International": "Harman International Industries",
    "Google": "Alphabet Inc.",
    "Ford Motor Company": "Ford Motor Company",
    "Valeo": "Valeo",
    "Denso": "Denso"
}
